### ISSUE TITLE
TSG S02 after change to undead give AI error

### ISSUE THREAD

**Issue by GregoryLundberg** [GregoryLundberg/wesnoth#28]
error ai/engine/cpp: side 2 : UNKNOWN aspect[village_value*ai_default_rca::aspect_attacks]

Appears on first undead recruited after

    [modify_side]
        side=2

        [ai]
            {ATTACK_DEPTH 2 3 4}
            grouping=no
            {NO_SCOUTS}
            village_value=3

            {QUANTITY recruitment_pattern (fighter)
            (fighter,fighter,scout,fighter)
            (fighter,archer,fighter,archer,scout)}
        [/ai]
    [/modify_side]

**Comment by GregoryLundberg** [comment]
Testing:

1) Same recruit list: no effect
2) Same recruit pattern: no effect
3) Remove recruit patter: no effect
4) Gold = -1000 (no recruits appear): no effect
5) 16 cases for macro ... various effects, see attachment

[results.txt](https://github.com/GregoryLundberg/wesnoth/files/455673/results.txt)

**Comment by GregoryLundberg** [comment]
To reproduce:

New Campaign: TSG
S01: Long-move Deoran to the fort to get Sir Gerrick, then kill the leader down south. End Turn on vicrory

S02: Long-move Deoran to the citadel. Hylas appears.
At this point I kill the two henchmen so they don't attack. This is optional.
With Hylas having just appeared on the map press End Turn

The leader down south will comment.
The leader down south will recruit undead.
The console message should appear.
Sir Gerrick will comment.
The crash will occur.

**Comment by mattsc** [comment]
I have figured out what is going on.  The merging of the two cfgs here:
https://github.com/wesnoth/wesnoth/blob/master/src/ai/manager.cpp#L168
does not work correctly when they do not have the same length and order for all the [aspect] tags.  In this case, cfg_ is a full config with all the aspects, while cfg contains only 4 (I had attack_depth commented out in my tests).

It collected and annotated what's in the two cfgs, and how the result looks after the merger here:
http://pastebin.com/pWWuDZXu

I don't know how to solve this, but I bet you can take it from here.

**Comment by CelticMinstrel** [comment]
That at least explains the warning. I'm not sure if it can explain the crash, but I guess we'll find out after I fix the warning.

**Comment by GregoryLundberg** [comment]
fixed
